### ISSUE TITLE
일별 데이터 처리

### ISSUE THREAD

**Issue by jiyong1** [woowa-techcamp-2021/cashbook-20#26]
- [x] API Server에서 일별로 묶어 데이터를 제공한다.
- [x] Client에서 비동기로 데이터를 요청 및 응답받는다
- 받은 데이터를 기반으로 페이지를 렌더링한다. (메인페이지, 원형 그래프는 추후에 진행)

**Comment by Kyun2da** [comment]
클라이언트쪽 미들웨어와 mutation이 상당히 인상적이었습니다~ 잘봤습니다.!
